project:
  type: website
  render:
    - "*.qmd"
    - "!2027.qmd"

website:
  title: "Advances in Spatial Machine Learning"
  description: "A workshop on open questions and challenges in spatial machine learning."
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: outcomes.qmd
        text: Outcomes
    right:
      - text: Past editions
        menu:
          - href: 2026.qmd
            text: 2026 workshop
          - href: 2025.qmd
            text: 2025 workshop
  page-footer:
    left: "Advances in Spatial Machine Learning"
    right: 
      - "Built with Quarto"
      - icon: github
        href: https://github.com/advsml/advsml.github.io

format:
  html:
    lang: en
    grid:
      body-width: 1000px
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
